import { Question } from "./types";

export const QUESTIONS: Question[] = [
  // ============ FRONTEND ============
  {
    id: "fe-e1",
    mode: "frontend",
    difficulty: "easy",
    question: "What is the difference between `==` and `===` in JavaScript?",
    hints: ["Think about type coercion", "One checks value, the other checks value AND type"],
    expectedKeywords: ["type coercion", "strict equality", "loose equality", "type conversion", "value and type", "no coercion"],
    followUp: "Can you give an example where `==` returns true but `===` returns false?",
    topic: "JavaScript Basics",
  },
  {
    id: "fe-e2",
    mode: "frontend",
    difficulty: "easy",
    question: "What is the CSS box model? Describe its components.",
    hints: ["Think about the layers around content", "There are 4 main parts"],
    expectedKeywords: ["content", "padding", "border", "margin", "box-sizing", "width", "height"],
    followUp: "How does `box-sizing: border-box` change the default behavior?",
    topic: "CSS Fundamentals",
  },
  {
    id: "fe-e3",
    mode: "frontend",
    difficulty: "easy",
    question: "What is the difference between `let`, `const`, and `var` in JavaScript?",
    hints: ["Think about scope and mutability", "Block scope vs function scope"],
    expectedKeywords: ["block scope", "function scope", "hoisting", "reassign", "const immutable", "let block", "var function", "temporal dead zone"],
    followUp: "What happens if you try to access a `let` variable before its declaration?",
    topic: "JavaScript Basics",
  },
  {
    id: "fe-m1",
    mode: "frontend",
    difficulty: "medium",
    question: "Explain the virtual DOM and how React uses it for efficient rendering.",
    hints: ["It's an in-memory representation", "Think about diffing and reconciliation"],
    expectedKeywords: ["in-memory", "lightweight copy", "diffing", "reconciliation", "batch updates", "minimal DOM operations", "re-render", "virtual tree"],
    followUp: "What is React Fiber and how does it improve upon the original reconciliation algorithm?",
    topic: "React Core",
  },
  {
    id: "fe-m2",
    mode: "frontend",
    difficulty: "medium",
    question: "What is the difference between `useEffect` and `useLayoutEffect` in React?",
    hints: ["Think about when they run relative to painting", "One is synchronous, one is asynchronous"],
    expectedKeywords: ["after paint", "before paint", "synchronous", "asynchronous", "layout", "DOM mutations", "visual updates", "blocking"],
    followUp: "When would you specifically choose useLayoutEffect over useEffect?",
    topic: "React Hooks",
  },
  {
    id: "fe-m3",
    mode: "frontend",
    difficulty: "medium",
    question: "How does CSS specificity work? Explain the specificity hierarchy.",
    hints: ["Think about inline styles, IDs, classes, elements", "There's a scoring system"],
    expectedKeywords: ["inline styles", "id selector", "class selector", "element selector", "specificity score", "!important", "cascade", "weight"],
    followUp: "How would you resolve a specificity conflict without using !important?",
    topic: "CSS Specificity",
  },
  {
    id: "fe-h1",
    mode: "frontend",
    difficulty: "hard",
    question: "Explain how JavaScript's event loop works, including microtasks and macrotasks.",
    hints: ["Think about the call stack, task queue, and microtask queue", "Promises create microtasks"],
    expectedKeywords: ["call stack", "task queue", "microtask queue", "macrotask", "event loop", "Promise", "setTimeout", "requestAnimationFrame", "execution context"],
    followUp: "In what order would these execute: setTimeout(0), Promise.resolve().then(), requestAnimationFrame?",
    topic: "JavaScript Runtime",
  },
  {
    id: "fe-h2",
    mode: "frontend",
    difficulty: "hard",
    question: "Design a performant infinite scroll implementation. What are the key considerations?",
    hints: ["Think about virtualization, intersection observer, memory management"],
    expectedKeywords: ["intersection observer", "virtualization", "windowing", "pagination", "memory management", "debounce", "throttle", "DOM nodes", "recycle", "placeholder"],
    followUp: "How would you handle scroll position restoration when navigating back to this page?",
    topic: "Performance",
  },
  {
    id: "fe-h3",
    mode: "frontend",
    difficulty: "hard",
    question: "Explain how a JavaScript bundler like Webpack works under the hood. What are the key phases?",
    hints: ["Think about dependency graphs, loaders, and plugins", "Entry point to output bundle"],
    expectedKeywords: ["dependency graph", "entry point", "loaders", "plugins", "chunks", "tree shaking", "code splitting", "module resolution", "AST", "bundle"],
    followUp: "How does tree shaking work and what conditions must be met for it to be effective?",
    topic: "Build Tools",
  },

  // ============ BACKEND ============
  {
    id: "be-e1",
    mode: "backend",
    difficulty: "easy",
    question: "What is the difference between SQL and NoSQL databases? When would you choose each?",
    hints: ["Think about structure, scalability, and use cases"],
    expectedKeywords: ["relational", "schema", "flexible schema", "horizontal scaling", "ACID", "joins", "document", "key-value", "structured data", "unstructured"],
    followUp: "Can you name specific examples of each type and their typical use cases?",
    topic: "Databases",
  },
  {
    id: "be-e2",
    mode: "backend",
    difficulty: "easy",
    question: "Explain the difference between authentication and authorization.",
    hints: ["One is about identity, the other is about permissions"],
    expectedKeywords: ["identity", "who you are", "permissions", "what you can do", "login", "access control", "verify", "credentials", "roles"],
    followUp: "How does OAuth 2.0 handle both authentication and authorization?",
    topic: "Security",
  },
  {
    id: "be-e3",
    mode: "backend",
    difficulty: "easy",
    question: "What are HTTP status codes? Name the main categories and give examples.",
    hints: ["Think about the 1xx through 5xx ranges"],
    expectedKeywords: ["200", "201", "301", "400", "401", "403", "404", "500", "informational", "success", "redirect", "client error", "server error"],
    followUp: "What's the difference between a 401 and 403 response?",
    topic: "HTTP",
  },
  {
    id: "be-m1",
    mode: "backend",
    difficulty: "medium",
    question: "Explain RESTful API design principles. What makes an API truly RESTful?",
    hints: ["Think about resources, HTTP methods, statelessness"],
    expectedKeywords: ["stateless", "resources", "HTTP methods", "GET", "POST", "PUT", "DELETE", "HATEOAS", "uniform interface", "idempotent", "URI", "status codes"],
    followUp: "How does REST compare to GraphQL in terms of over-fetching and under-fetching?",
    topic: "API Design",
  },
  {
    id: "be-m2",
    mode: "backend",
    difficulty: "medium",
    question: "What is database indexing? How does it improve query performance?",
    hints: ["Think about B-trees and trade-offs", "Like an index in a book"],
    expectedKeywords: ["B-tree", "lookup speed", "trade-off", "write performance", "disk I/O", "index scan", "full table scan", "composite index", "cardinality"],
    followUp: "When would adding an index actually hurt performance?",
    topic: "Database Optimization",
  },
  {
    id: "be-m3",
    mode: "backend",
    difficulty: "medium",
    question: "Explain middleware in the context of web frameworks. How does the middleware pipeline work?",
    hints: ["Think about request/response processing chain", "Each middleware can modify or pass along"],
    expectedKeywords: ["request", "response", "pipeline", "chain", "next", "order matters", "logging", "authentication", "error handling", "modify"],
    followUp: "How would you implement error-handling middleware that catches all unhandled errors?",
    topic: "Web Frameworks",
  },
  {
    id: "be-h1",
    mode: "backend",
    difficulty: "hard",
    question: "Design a rate limiter for a distributed system. What algorithms and data structures would you use?",
    hints: ["Consider token bucket, sliding window, or leaky bucket", "Think about distributed state"],
    expectedKeywords: ["token bucket", "sliding window", "leaky bucket", "Redis", "distributed", "atomic operations", "TTL", "race condition", "consistency", "throughput"],
    followUp: "How would you handle rate limiting across multiple data centers?",
    topic: "Distributed Systems",
  },
  {
    id: "be-h2",
    mode: "backend",
    difficulty: "hard",
    question: "Explain the CAP theorem and how it applies to database selection for different use cases.",
    hints: ["Consistency, Availability, Partition tolerance — pick two", "Think about real-world trade-offs"],
    expectedKeywords: ["consistency", "availability", "partition tolerance", "trade-off", "CP", "AP", "eventual consistency", "strong consistency", "network partition", "distributed"],
    followUp: "Is it truly 'pick two' or is the reality more nuanced? Explain.",
    topic: "Distributed Systems",
  },
  {
    id: "be-h3",
    mode: "backend",
    difficulty: "hard",
    question: "How would you design a message queue system? Compare different messaging patterns.",
    hints: ["Think about pub/sub, point-to-point, and guarantees", "Consider exactly-once delivery"],
    expectedKeywords: ["pub/sub", "point-to-point", "at-least-once", "at-most-once", "exactly-once", "dead letter queue", "backpressure", "consumer groups", "offset", "acknowledgment"],
    followUp: "How does Kafka achieve high throughput while maintaining message ordering?",
    topic: "Message Queues",
  },

  // ============ SYSTEM DESIGN ============
  {
    id: "sd-e1",
    mode: "system-design",
    difficulty: "easy",
    question: "What is horizontal vs vertical scaling? When would you use each?",
    hints: ["Think about adding more machines vs making one machine bigger"],
    expectedKeywords: ["horizontal", "vertical", "scale out", "scale up", "load balancer", "stateless", "cost", "limit", "distributed", "single machine"],
    followUp: "What challenges arise when you switch from vertical to horizontal scaling?",
    topic: "Scaling",
  },
  {
    id: "sd-e2",
    mode: "system-design",
    difficulty: "easy",
    question: "What is caching and why is it important in system design?",
    hints: ["Think about speed, cost of repeated computation, and where caches can live"],
    expectedKeywords: ["speed", "latency", "memory", "TTL", "cache invalidation", "hit rate", "miss", "CDN", "Redis", "in-memory", "expiration"],
    followUp: "What are common cache invalidation strategies?",
    topic: "Caching",
  },
  {
    id: "sd-e3",
    mode: "system-design",
    difficulty: "easy",
    question: "Explain what a load balancer does and name common load balancing algorithms.",
    hints: ["Distributes traffic across servers", "Round robin is the simplest"],
    expectedKeywords: ["distribute", "traffic", "round robin", "least connections", "health check", "sticky sessions", "reverse proxy", "availability", "redundancy"],
    followUp: "What happens when a load balancer itself fails? How do you prevent that?",
    topic: "Load Balancing",
  },
  {
    id: "sd-m1",
    mode: "system-design",
    difficulty: "medium",
    question: "Design a URL shortener like bit.ly. Walk through the key components.",
    hints: ["Think about encoding, storage, redirection, and analytics"],
    expectedKeywords: ["hash", "base62", "encoding", "database", "redirect", "301", "302", "collision", "analytics", "read-heavy", "cache", "unique ID"],
    followUp: "How would you handle custom aliases and prevent abuse?",
    topic: "System Design",
  },
  {
    id: "sd-m2",
    mode: "system-design",
    difficulty: "medium",
    question: "How would you design a notification system that supports email, SMS, and push notifications?",
    hints: ["Think about queues, templates, and delivery guarantees"],
    expectedKeywords: ["message queue", "template", "priority", "retry", "delivery status", "webhook", "rate limiting", "preference", "channel", "async"],
    followUp: "How would you handle notification preferences and unsubscribe functionality?",
    topic: "System Design",
  },
  {
    id: "sd-h1",
    mode: "system-design",
    difficulty: "hard",
    question: "Design a real-time collaborative document editor like Google Docs. Focus on conflict resolution.",
    hints: ["Think about OT or CRDT, WebSockets, and consistency"],
    expectedKeywords: ["operational transformation", "CRDT", "WebSocket", "conflict resolution", "cursor position", "version", "merge", "real-time", "eventual consistency", "collaboration"],
    followUp: "How would OT and CRDT approaches differ in terms of server requirements?",
    topic: "Real-time Systems",
  },
  {
    id: "sd-h2",
    mode: "system-design",
    difficulty: "hard",
    question: "Design a distributed search engine that can index billions of documents. Describe the architecture.",
    hints: ["Think about crawling, indexing, ranking, and serving"],
    expectedKeywords: ["crawler", "inverted index", "MapReduce", "sharding", "ranking", "PageRank", "TF-IDF", "distributed", "replication", "query parsing", "relevance"],
    followUp: "How would you handle real-time indexing for frequently updated content?",
    topic: "Search Systems",
  },

  // ============ DSA ============
  {
    id: "dsa-e1",
    mode: "dsa",
    difficulty: "easy",
    question: "What is the time complexity of searching in a hash map? Why is it O(1) on average?",
    hints: ["Think about the hash function and bucket lookups", "What happens with collisions?"],
    expectedKeywords: ["O(1)", "hash function", "bucket", "collision", "chaining", "constant time", "key", "index", "worst case O(n)"],
    followUp: "What causes worst-case O(n) performance in a hash map?",
    topic: "Hash Maps",
  },
  {
    id: "dsa-e2",
    mode: "dsa",
    difficulty: "easy",
    question: "Explain the difference between a stack and a queue. Give real-world examples of each.",
    hints: ["Think LIFO vs FIFO", "Browser history vs printer queue"],
    expectedKeywords: ["LIFO", "FIFO", "last in first out", "first in first out", "push", "pop", "enqueue", "dequeue", "browser back", "print queue"],
    followUp: "How would you implement a queue using two stacks?",
    topic: "Basic Data Structures",
  },
  {
    id: "dsa-e3",
    mode: "dsa",
    difficulty: "easy",
    question: "What is Big O notation and why is it important for evaluating algorithms?",
    hints: ["Think about describing growth rate", "Worst-case analysis"],
    expectedKeywords: ["growth rate", "worst case", "time complexity", "space complexity", "scalability", "input size", "upper bound", "O(n)", "O(1)", "asymptotic"],
    followUp: "What is the difference between O(n log n) and O(n²) for large inputs?",
    topic: "Complexity Analysis",
  },
  {
    id: "dsa-m1",
    mode: "dsa",
    difficulty: "medium",
    question: "Explain how a binary search tree works. What are its advantages and when does it degrade?",
    hints: ["Think about the ordering property", "What happens when it's unbalanced?"],
    expectedKeywords: ["left smaller", "right larger", "O(log n)", "balanced", "unbalanced", "degrade to O(n)", "in-order traversal", "sorted", "search", "insert"],
    followUp: "How do self-balancing trees like AVL or Red-Black trees solve the degradation problem?",
    topic: "Trees",
  },
  {
    id: "dsa-m2",
    mode: "dsa",
    difficulty: "medium",
    question: "Compare merge sort and quicksort. What are the trade-offs between them?",
    hints: ["Think about worst case, space, and practical performance"],
    expectedKeywords: ["O(n log n)", "merge sort stable", "quicksort in-place", "worst case O(n²)", "pivot", "divide and conquer", "space complexity", "cache friendly", "stable"],
    followUp: "Why is quicksort often faster in practice despite having a worse worst-case?",
    topic: "Sorting",
  },
  {
    id: "dsa-m3",
    mode: "dsa",
    difficulty: "medium",
    question: "What is dynamic programming? Explain the difference between top-down and bottom-up approaches.",
    hints: ["Think about overlapping subproblems and optimal substructure"],
    expectedKeywords: ["overlapping subproblems", "optimal substructure", "memoization", "tabulation", "top-down", "bottom-up", "recursive", "iterative", "cache results"],
    followUp: "Walk through how you would solve the Fibonacci sequence using both approaches.",
    topic: "Dynamic Programming",
  },
  {
    id: "dsa-h1",
    mode: "dsa",
    difficulty: "hard",
    question: "Explain graph traversal algorithms BFS and DFS. When would you choose one over the other?",
    hints: ["Think about the data structures they use and what problems they solve best"],
    expectedKeywords: ["breadth-first", "depth-first", "queue", "stack", "shortest path", "topological sort", "level order", "backtracking", "connected components", "cycle detection"],
    followUp: "How would you detect a cycle in a directed graph using DFS?",
    topic: "Graphs",
  },
  {
    id: "dsa-h2",
    mode: "dsa",
    difficulty: "hard",
    question: "Explain the trie data structure. What problems is it particularly good at solving?",
    hints: ["Think about prefix matching and autocomplete"],
    expectedKeywords: ["prefix tree", "character nodes", "autocomplete", "prefix matching", "O(m)", "word length", "space efficient", "dictionary", "spell check", "children map"],
    followUp: "How would you optimize a trie for memory when storing a large dictionary?",
    topic: "Advanced Data Structures",
  },
  {
    id: "dsa-h3",
    mode: "dsa",
    difficulty: "hard",
    question: "What is the A* search algorithm? How does it differ from Dijkstra's algorithm?",
    hints: ["Think about heuristics and informed search"],
    expectedKeywords: ["heuristic", "f(n) = g(n) + h(n)", "admissible", "priority queue", "shortest path", "informed search", "Dijkstra no heuristic", "optimal", "graph traversal"],
    followUp: "What properties must a heuristic have for A* to guarantee finding the optimal path?",
    topic: "Graph Algorithms",
  },
];

export function getQuestionsByModeAndDifficulty(mode: string, difficulty: string): Question[] {
  return QUESTIONS.filter((q) => q.mode === mode && q.difficulty === difficulty);
}

export function getRandomQuestion(mode: string, difficulty: string, excludeIds: string[]): Question | null {
  const available = QUESTIONS.filter(
    (q) => q.mode === mode && q.difficulty === difficulty && !excludeIds.includes(q.id)
  );
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}
